version: "3.9"
services:
  database:
    image: mongo
    container_name: database
    ports:
      - '27017:27017'
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '8000:3001'
    links:
      - database
    restart: always
  frontend:
    build: './frontend'
    container_name: frontend
    ports:
      - '8080:3000'
    links:
      - backend
    stdin_open: true
    tty: true